import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SavedStoriesProvider } from "@/contexts/SavedStoriesContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hacker News Clone",
  description: "Generated by MoMa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <SavedStoriesProvider><body className={inter.className}>{children}</body></SavedStoriesProvider>

    </html>
  );
}
